export type ArchiveMedia = {
  intro: string;
  description: string;
  practices: string;
  place: string;
  images: [string, string, string];
};

const series = (folder: string, hero: string, processOne: string, processTwo: string): [string, string, string] => [
  `/images/archive/${folder}/${hero}`,
  `/images/archive/${folder}/${processOne}`,
  `/images/archive/${folder}/${processTwo}`,
];

export const archiveMedia: Record<string, ArchiveMedia> = {
  "pablo-merchante-introduccion": { intro: "Una inmersión en la materia pictórica para aprender a utilizar el error y lo fortuito como herramientas de creación.", description: "Pablo Merchante compartió ejercicios de experimentación, una demostración de su proceso y acompañamiento individual para construir imágenes desde la intuición, el criterio plástico y la relación directa con los materiales.", practices: "Pintura y experimentación matérica", place: "Madrid", images: series("pablo-merchante/introducción a lo produndo de la pintura", "IMG_3938.jpeg", "IMG_4062.jpeg", "IMG_4154.jpeg") },
  "pablo-merchante-edicion-2": { intro: "Segunda edición de una experiencia dedicada a entrar en lo profundo de la pintura.", description: "El grupo trabajó con óleo, spray, gesso y dibujo para transformar accidentes, decisiones y correcciones en recursos pictóricos capaces de sostener una obra personal.", practices: "Pintura y materia", place: "Madrid", images: series("pablo-merchante/introducción a lo produndo de la pintura", "IMG_9597.jpeg", "IMG_9687.jpeg", "IMG_9757.jpeg") },
  "ignacio-rivas": { intro: "Collage analógico para componer desde el caos, la intuición y el juego.", description: "Ignacio Rivas propuso cortar, desplazar y volver a relacionar imágenes encontradas. La experiencia convirtió el collage en un campo de pruebas para descubrir asociaciones inesperadas y construir una narrativa visual propia.", practices: "Collage y composición", place: "Madrid", images: series("ignacio-rivas", "hero.png", "process-01.png", "process-02.png") },
  "santiago-picatoste-edicion-1": { intro: "Una jam session pictórica para producir en compañía y llevar la pintura fuera de sus rutinas.", description: "La primera edición de Fábrica de deseos reunió experimentación, intercambio y trabajo intensivo en una nave industrial, acompañados por la práctica pictórica de Santiago Picatoste.", practices: "Pintura y creación colectiva", place: "Málaga", images: series("santiago-picatoste", "hero.jpg", "process-01.png", "process-02.png") },
  "santiago-picatoste-edicion-2": { intro: "Segunda edición del retiro de creación y experimentación pictórica.", description: "Durante una experiencia inmersiva, el grupo ensayó nuevas relaciones entre gesto, color, escala y materia, compartiendo procesos y conversaciones alrededor de la pintura contemporánea.", practices: "Pintura y retiro creativo", place: "Málaga", images: series("santiago-picatoste", "hero.jpg", "process-02.png", "process-01.png") },
  "santiago-picatoste": { intro: "Dos ediciones de una jam session pictórica para producir en compañía y llevar la pintura fuera de sus rutinas.", description: "Fábrica de deseos reunió experimentación, intercambio y trabajo intensivo en una nave industrial. Santiago Picatoste acompañó un proceso inmersivo alrededor del gesto, el color, la escala y la materia.", practices: "Pintura y retiro creativo", place: "Málaga", images: series("santiago-picatoste", "243E7BC2-4800-4BF8-85AE-30894197986F_1_102_o.jpeg", "603BF8D2-720D-42C9-97A8-DEB596F77AE9_1_105_c.jpeg", "69DBCBC7-BE18-4813-A784-FCA396B62BE7_1_102_o.jpeg") },
  "movimiento-cuerpo-pintura": { intro: "Bailar, pintar y llevar el lenguaje poético del cuerpo hasta la superficie.", description: "Laura López Balza y Guadalupe Ramón articularon ejercicios de expresión corporal, danza y acción pictórica. El movimiento funcionó como impulso para pintar sin condicionamientos y celebrar el proceso creativo.", practices: "Movimiento, performance y pintura", place: "Sevilla", images: series("movimiento-cuerpo-pintura", "hero.jpg", "process-01.jpg", "process-02.jpg") },
  "movimiento-cuerpo-pintura-edicion-2": { intro: "Una segunda experiencia para fusionar cuerpo, gesto y pintura.", description: "A partir de propuestas performativas, el grupo investigó cómo una acción corporal puede dejar huella y convertirse en materia pictórica, alternando ejercicios individuales y colectivos.", practices: "Danza, cuerpo y pintura", place: "Madrid", images: series("movimiento-cuerpo-pintura", "hero.jpg", "process-02.jpg", "process-01.jpg") },
  ampparito: { intro: "Un fin de semana donde la única premisa fue romper las reglas del juego.", description: "Después de alterar objetos, significados y situaciones dentro del estudio, el grupo desarrolló una intervención urbana colectiva. Ampparito acompañó una forma de añadir algo poético y efímero a lo que ya existe en la ciudad.", practices: "Arte conceptual e intervención urbana", place: "Madrid", images: series("ampparito", "hero.jpg", "process-01.jpg", "process-02.jpg") },
  "multiple-editions": { intro: "Revelar las capas de la imagen a través de la serigrafía contemporánea.", description: "Desde el taller de Diego Mena, el grupo aprendió las bases de la serigrafía y las puso a prueba con color, textura y composición. Cada participante desarrolló una pequeña serie personal sobre papel.", practices: "Serigrafía y edición", place: "Carabanchel · Madrid", images: series("multiple-editions", "hero..jpeg", "647E0358-F3D8-4F73-A122-901D767673C5_1_105_c.jpeg", "7802742C-BF08-473A-B9DC-D7BE97A17F92_1_105_c.jpeg") },
  rosh: { intro: "De la deriva urbana a un laboratorio de imágenes analógicas y digitales.", description: "Rosh propuso recolectar texturas y escenas de la calle, combinarlas mediante collage y herramientas digitales y trasladar ese archivo a una composición pictórica personal.", practices: "Deriva, collage y pintura", place: "Madrid", images: series("rosh", "2AAAF447-406D-4681-ABAB-F3460407ADB2_1_105_c.jpeg", "34E6E911-86E1-4392-A111-6C6998DCACF1_1_105_c.jpeg", "96A23E29-4822-4245-994C-E40AB7515B61_1_105_c.jpeg") },
  "justine-menard": { intro: "Aire, fuego e intuición para entrar en el universo del vidrio soplado.", description: "Justine Menard compartió técnicas de soplado y vidrio sólido. Pequeños objetos, pruebas de color y formas naturales funcionaron como bocetos para diseñar esculturas contemporáneas.", practices: "Vidrio soplado y escultura", place: "Barcelona", images: series("justine-menard", "33CDF883-479C-42FB-AC47-A9700EAFB4CF_1_102_o.jpeg", "5B030DEE-0EE9-43B8-B0DF-9F3D007BF91F_1_105_c.jpeg", "628BDD94-F540-4CF0-AE0D-74A849073DAB_1_102_o.jpeg") },
  "justine-menard-edicion-2": { intro: "Segunda edición de una conversación práctica entre cuerpo, fuego y vidrio.", description: "La experiencia volvió a poner el material en el centro: observar su temperatura, responder a su movimiento y descubrir formas mediante técnicas de soplado y modelado.", practices: "Vidrio y escultura", place: "Madrid", images: series("justine-menard", "65748590-6013-4644-81E8-AA263DF38164_1_105_c.jpeg", "6E33D600-B9FC-40DA-AA6C-DA91F13C3D78_1_105_c.jpeg", "A162F461-9CC3-4721-B385-74EC589DCBD4_1_102_o.jpeg") },
  "guido-sarli": { intro: "Un laboratorio de movimiento para bailar aquello que sucede en los límites.", description: "Guido Sarli acompañó ejercicios de percepción, improvisación y composición corporal. El taller investigó el espacio intermedio entre gesto cotidiano, presencia y práctica escénica.", practices: "Movimiento y performance", place: "Madrid", images: series("guido-sarli", "4F261CD2-F266-42E3-8924-4C6E76C28762_1_105_c.jpeg", "8467D140-69C4-42C5-8993-5D0CBA392498_1_105_c.jpeg", "9AF27517-B6F0-4E0F-B59D-E67F923E10D4_1_105_c.jpeg") },
  "javier-ruiz": { intro: "Un retiro interdisciplinar para mirar la pintura tras bambalinas.", description: "Javier Ruiz propuso atender a las decisiones invisibles del proceso pictórico: preparación, color, corrección y montaje. La convivencia permitió sostener una práctica intensiva y compartir herramientas entre disciplinas.", practices: "Pintura y creación interdisciplinar", place: "Madrid", images: series("javier-ruiz/la pintura tras bambalinas", "02D5AF6C-6A78-4AAF-AA2F-91072FBA95FC_1_105_c.jpeg", "164A2828-7D17-4C1E-B84F-A78D27039DEC_1_105_c.jpeg", "3814F7EA-E66F-443E-B794-B656E212D798_1_102_o.jpeg") },
  "catalina-romero": { intro: "Herramientas para fotografiar una obra sin perder su materia, escala ni color.", description: "Catalina Romero compartió criterios de iluminación, encuadre, cámara y edición para producir registros fieles y útiles de piezas artísticas, combinando explicación técnica y práctica directa.", practices: "Fotografía y documentación de obra", place: "Madrid", images: series("catalina-romero", "539256B4-3763-4199-AA88-76CBB6DD0706_1_105_c.jpeg", "571F5B52-F650-4789-8979-CBCD080DA729_1_105_c.jpeg", "5F665CE4-6E54-42B1-99F1-E8CD6988334A_4_5005_c.jpeg") },
  "juan-narowe": { intro: "El dibujo como herramienta para construir relatos contemporáneos.", description: "Juan Narowé acompañó ejercicios de observación, secuencia y composición para explorar cómo una imagen dibujada puede abrir una historia y relacionarse con otras sin cerrarla.", practices: "Dibujo y narrativa visual", place: "Madrid", images: series("juan-narowe", "0B81C8CA-66FC-4156-A2A0-AF1E8B14553F_1_105_c.jpeg", "3EA6B61F-25FA-4B19-B454-2B47D5B2A76F_1_105_c.jpeg", "436A3CD7-64B4-48FF-A34F-D973A34549D6_1_105_c.jpeg") },
  "jan-monclus": { intro: "Nuevas prácticas de pintura figurativa alrededor de lo absurdo.", description: "Jan Monclús propuso desplazar escenas, gestos y referencias cotidianas para construir imágenes donde el humor, la extrañeza y la pintura pudieran convivir.", practices: "Pintura figurativa", place: "Fresca. La Nave · Madrid", images: series("jan-monclus", "29804016-D9F8-4111-A354-8A1D04674B12_1_105_c.jpeg", "7EB20054-B9A3-44FD-AB39-83795BF0766C_1_105_c.jpeg", "A6D26496-2177-4EAD-BFB2-0AC3DEB0F657_1_105_c.jpeg") },
  "julio-galindo": { intro: "Dos ediciones dedicadas a construir figuras en cerámica desde la intuición, el color y el volumen.", description: "En 2024 y 2026, Julio Galindo compartió técnicas de modelado, engobes y cocción para desarrollar pequeñas esculturas cerámicas, atendiendo a la expresividad de la forma y a las decisiones que aparecen durante el hacer.", practices: "Cerámica artística y escultura", place: "Fresca. La Nave · Madrid", images: series("julio-galindo", "088547FA-7CAB-4684-87E8-D06DAD119933_1_105_c.jpeg", "1AC2AE38-FE52-4A1E-B97B-7A471ABD48A1_1_105_c.jpeg", "47BD0B81-EC7C-45BA-838A-D5BB2D5C068C_4_5005_c.jpeg") },
  "paula-cid-cerezo": { intro: "Una deriva por Carabanchel para revelar registros de lo aparentemente invisible.", description: "Paula Cid Cerezo introdujo técnicas de estampación y acompañó una búsqueda urbana de texturas, rastros y formas. Los hallazgos se trasladaron al papel mediante monotipo, punta seca, frottage y gofrado.", practices: "Grabado, deriva y autoedición", place: "Carabanchel · Madrid", images: series("paula-cid-cerezo", "162CB206-2456-4813-8B91-84D9881AAFF9_1_105_c.jpeg", "49D01CF1-AA05-4D12-B459-968F5F8C74EA_1_105_c.jpeg", "4FF6DC58-4E55-48CA-B774-023C9F251F60_1_105_c.jpeg") },
  "sophie-aguilera-flores": { intro: "Escultura floral en porcelana entre observación, modelado y color.", description: "Sophie Aguilera acompañó la construcción de formas botánicas en porcelana, desde las primeras pruebas hasta la composición, decoración y cocción de pequeñas esculturas.", practices: "Porcelana y escultura", place: "Fresca. La Nave · Madrid", images: series("sophie-aguilera-flores", "200D25F8-57E4-4E29-A9E0-EE6530E753CB_1_105_c.jpeg", "2A6A7513-4C5D-4860-9B0A-1EB5A004D37D_1_105_c.jpeg", "362E84E3-68DF-4EE8-B770-9279B1479256_1_105_c.jpeg") },
  "miguel-gomez-losada": { intro: "Qué pintar y cómo: un acercamiento a la voz propia.", description: "Miguel Gómez Losada invitó a elegir un estado de ánimo y acercarlo a la pintura mediante metáforas, color y formas. Los ejercicios evitaron la literalidad para aproximar cada obra al hecho poético.", practices: "Pintura, color y composición", place: "Fresca. La Nave · Madrid", images: series("miguel-gomez-losada", "111937D6-6D27-42CB-B371-47432DB11D6B_1_105_c.jpeg", "2DD8012E-2720-4EFA-888F-72F35FF0D56C_1_105_c.jpeg", "63DF50AE-30C0-49C6-9EFE-99D1BC9CE238_1_105_c.jpeg") },
  "eloy-arribas": { intro: "Materia y memoria para reflexionar sobre cómo habitamos el presente.", description: "Eloy Arribas propuso trabajar el dibujo y materiales no convencionales en gran formato. La experiencia trasladó al grupo algunos mecanismos de su práctica: destruir conceptos, reconstruirlos plásticamente y atender a su carga sensible.", practices: "Dibujo, pintura y materia", place: "Fresca. La Nave · Madrid", images: series("eloy-arribas", "12214418-A4BE-4DA2-948B-4FDE6A0B0B0B_1_105_c.jpeg", "457996D8-2749-4418-9C74-10C0A6251C6A_1_105_c.jpeg", "636F2887-5BCC-4307-97E3-06B51FFD9C12_1_105_c.jpeg") },
  "carla-souto": { intro: "Una introducción al modelado en cera para diseñar una pieza de joyería.", description: "Carla Souto compartió herramientas de la técnica de cera perdida. El taller recorrió el diseño, el modelado y las decisiones de volumen y textura necesarias para preparar una pieza destinada a fundición.", practices: "Joyería y modelado en cera", place: "Fresca. La Nave · Madrid", images: series("carla-souto", "07CB100E-F2E7-41D5-BFF3-D3A447921F26_4_5005_c.jpeg", "09DE8D41-0692-44E3-B5B0-3393A956B8A1_1_102_o.jpeg", "190B9F3A-EC84-41A4-B998-8FFEF0E264F4.jpeg") },
  "bendita-la-mesa": { intro: "Crear objetos cerámicos para celebrar los gestos de la mesa compartida.", description: "Brenda Ranieri acompañó el modelado de platos, cuencos, jarrones y objetos cotidianos. La sesión culminó con una cata de vinos naturales de Belén Arnedo: una mesa de trabajo convertida en espacio de encuentro y brindis.", practices: "Cerámica y cultura gastronómica", place: "Fresca. La Nave · Madrid", images: series("bendita-la-mesa", "1F3B2B3F-BAE6-41A8-941B-D487CFE4903B_1_105_c.jpeg", "2E39FE52-A272-4D26-8350-C016A288F553_1_105_c.jpeg", "5C97AE2A-193F-41DC-8627-AD42F0FCC3CC_1_102_o.jpeg") },
  "joyeria-ceramica-metal": { intro: "Dos materiales unidos por el fuego para diseñar y construir una joya personal.", description: "Brenda Ranieri acompañó el diseño de piezas cerámicas con incrustaciones de metal. Después de la cocción, Chantal Douer guio una segunda sesión dedicada a crear en plata los elementos que sostienen, intervienen o contienen cada joya.", practices: "Cerámica, metal y joyería", place: "Fresca. La Nave · Madrid", images: series("joyeria-ceramica-metal", "148CF6A4-1CD7-4E0D-91A3-D8F14B130BFF_1_105_c.jpeg", "243C0E79-FB1F-470A-B709-A98AF09C9969_1_105_c.jpeg", "2C5F10C9-23F1-40BE-8BEE-424997A016E8_1_105_c.jpeg") },
};
