export type ProgramItem = { number: string; type: string; title: string; subtitle?: string; artist: string; description: string; detail: string; image: string; alt: string; href?: string };
export type ProgramGroup = { slug: string; number: string; kicker: string; title: string; statement: string; description: string; pageDescription?: string; highlights?: string[]; image: string; items: ProgramItem[] };

const talleres: ProgramItem[] = [
  { number: "DM—01", type: "Derivas materiales · Taller", title: "Ese instante de luz", subtitle: "Rayogramas de una deriva", artist: "Ana Paes", description: "Un taller nocturno de fotografía sin cámara para registrar gestos y texturas del entorno. Una deriva por el barrio que continúa en la oscuridad de la nave.", detail: "II edición · 2 OCT 2026", image: "/images/program/derivas materiales/tarjetas/Ese instante de luz_Fresca la nave_rayogramas_fotografia_Madrid.jpeg", alt: "Imagen del taller de rayogramas Ese instante de luz", href: "/talleres/ese-instante-de-luz" },
  { number: "DM—02", type: "Derivas materiales · Taller", title: "Experimentación pictórica sobre cerámica", artist: "Ana Cano Brookbank", description: "Estampaciones, impresiones e intervenciones pictóricas para experimentar con huellas, líneas, manchas, capas y accidentes sobre cerámica.", detail: "II edición · 31 OCT — 01 NOV 2026", image: "/images/program/derivas materiales/tarjetas/Del papel a la porcelana.jpeg", alt: "Experimentación pictórica sobre cerámica con Ana Cano Brookbank", href: "/talleres/experimentacion-pictorica-sobre-ceramica" },
  { number: "DM—03", type: "Derivas materiales · Taller", title: "Micelio y textil", subtitle: "Micomateriales", artist: "Alejandra Díaz-Guerra", description: "Una aproximación práctica y ritual al micelio como agente vivo de creación, trabajando con fibras naturales y tiempos de crecimiento compartidos.", detail: "21 NOV + 12 DIC 2026", image: "/images/program/derivas materiales/tarjetas/Micelio y textil.jpeg", alt: "Imagen del taller Micelio y textil", href: "/talleres/micelio-y-textil" },
  { number: "DM—04", type: "Derivas materiales · Taller", title: "Arcillas silvestres y paisaje urbano", artist: "Luka Andeyro + Brenda Ranieri", description: "Un laboratorio para descubrir la arcilla en relación con el territorio y transformar materiales descartados del paisaje urbano en nuevas posibilidades cerámicas.", detail: "II edición · 27—29 NOV 2026", image: "/images/program/derivas materiales/tarjetas/Arcilla silvestre y paisaje urbano_ceramica_Madrid_Resca la nave .png", alt: "Imagen del taller Arcillas silvestres", href: "/talleres/arcillas-silvestres-y-paisaje-urbano" },
  { number: "DM—05", type: "Derivas materiales · Taller", title: "Criaturas elementales", subtitle: "Activación oracular", artist: "Cecilia Czornogas", description: "Escritura, dibujo y acuarela activados por un oráculo pictórico. Una práctica para jugar con la intuición, el azar y aquello que aparece durante el proceso.", detail: "II edición · 11 DIC 2026", image: "/images/program/derivas materiales/tarjetas/Criaturas elementales.jpeg", alt: "Imagen del taller Criaturas elementales", href: "/talleres/criaturas-elementales" },
  { number: "DM—06", type: "Derivas materiales · Taller", title: "Sirviendo simulaciones", subtitle: "La poética de lo cotidiano en cerámica", artist: "Sophie Aguilera Lester", description: "Un taller de escultura cerámica para explorar el bodegón y transformar objetos cotidianos en composiciones escultóricas que juegan con la ilusión óptica.", detail: "30—31 ENE 2027", image: "/images/program/derivas materiales/paginas/sirviendo-chasco/sirviendo-chasco-01.jpg", alt: "Plato de engaño en cerámica de Sophie Aguilera Lester", href: "/talleres/sirviendo-un-plato-bodegon" },
];

export const programGroups: ProgramGroup[] = [
  { slug: "talleres", number: "01", kicker: "Talleres", title: "Derivas materiales", statement: "Seguir lo que la materia propone.", description: "Talleres intensivos de fin de semana para aproximarse a una materia, una técnica o una pregunta desde la experimentación. Artistas y creadoras invitadas comparten sus saberes para observar, recolectar, transformar y dar forma.", pageDescription: "Derivas materiales propone un modo de aproximarse a la creación: partir de una materia, una técnica o una observación y dejar que el proceso abra recorridos inesperados. En cada taller intensivo de fin de semana, una artista o creadora invitada comparte sus saberes y acompaña un proceso de experimentación: observar, recolectar, transformar y dar forma.", image: "/images/program/rayogramas.png", items: talleres },
  { slug: "seminarios", number: "02", kicker: "Procesos cuatrimestrales", title: "Seminarios", statement: "Tiempo para que una práctica encuentre su forma.", description: "Programas de acompañamiento sostenido para desarrollar proyectos propios. Grupos reducidos, tutorías, conversación crítica y herramientas de producción permiten investigar, tomar decisiones y preparar una forma de compartir públicamente cada proceso.", image: "/images/program/procesos cuatrimestrales/Autoedicion.jpeg", items: [
    { number: "SE—01", type: "Seminario · Práctica artística", title: "En obra", subtitle: "Acompañamiento crítico para la práctica artística", artist: "Nacho Martín Silva", description: "Acompañamiento para desarrollar, poner a prueba y compartir un proyecto propio mediante tutorías, crítica de obra, conversación y una exposición colectiva.", detail: "Octubre 2026—marzo 2027", image: "/images/program/procesos cuatrimestrales/seminario en obra/64828F08-43DF-47D4-92A4-3DD8A97CD0C7_1_105_c.jpeg", alt: "Montaje y conversación durante el seminario En obra", href: "/seminarios/en-obra" },
    { number: "SE—02", type: "Seminario · Autoedición", title: "Autoedición", subtitle: "Herramientas para crear y producir una publicación.", artist: "Ana Bustelo", description: "Un proceso acompañado para idear, producir y presentar una publicación personal, desde la investigación y el boceto hasta sus acabados y puesta en público.", detail: "Febrero—mayo 2027", image: "/images/program/procesos cuatrimestrales/seminario-autoedicion/Open Studio_Libros a la fresca_37.png", alt: "Publicaciones realizadas en el seminario de autoedición", href: "/seminarios/autoedicion" },
  ] },
  { slug: "musica", number: "03", kicker: "Música", title: "Derivas sonoras", statement: "Seguir lo que la escucha propone.", description: "Un programa de investigación, creación y encuentro musical coproducido por Nina Polverino y Fresca. La Nave. Laboratorios, conciertos, prácticas de voz y retiros para investigar la música mientras se compone, se ensaya y se transforma.", image: "/images/program/derivas-sonoras/00-identidad-general.png", items: [
    { number: "DS—01", type: "Derivas sonoras · Laboratorio", title: "Laboratorio de canciones", artist: "Laicha", description: "Herramientas de composición puestas a disposición de la experimentación colectiva en un encuentro íntimo de creación.", detail: "Noviembre 2026 · 3 h", image: "/images/program/derivas-sonoras/01-laboratorio-canciones-laicha.png", alt: "Identidad visual del Laboratorio de canciones con Laicha" },
    { number: "DS—02", type: "Derivas sonoras · Microconciertos", title: "Microconciertos", artist: "Alumnado de Nina Polverino", description: "Encuentros breves donde distintas voces y procesos musicales comparten un mismo espacio de escucha.", detail: "Fecha a confirmar", image: "/images/program/derivas-sonoras/02-microconciertos-alumnado.png", alt: "Identidad visual de los microconciertos del alumnado de Nina Polverino" },
    { number: "DS—03", type: "Derivas sonoras · Concierto", title: "Conciertos experimentales", subtitle: "Sesión 01", artist: "Artistas invitadas", description: "Una sesión en vivo para poner a prueba sonidos, formas de escucha y relaciones inesperadas entre distintas prácticas musicales.", detail: "Fecha a confirmar", image: "/images/program/derivas-sonoras/03-conciertos-experimentales-sesion-01.png", alt: "Identidad visual de Conciertos experimentales, sesión 01" },
    { number: "DS—04", type: "Derivas sonoras · Retiro creativo", title: "Retiro creativo", subtitle: "Música, cuerpo y materia", artist: "Nina Polverino + Fresca. La Nave", description: "Un tiempo de inmersión para investigar la música desde la escucha, el cuerpo, el pensamiento y la materia.", detail: "Fecha a confirmar", image: "/images/program/derivas-sonoras/04-retiro-creativo.png", alt: "Identidad visual del retiro creativo de música, cuerpo y materia" },
  ] },
  { slug: "openings", number: "04", kicker: "Programa público", title: "Programa Público", statement: "Poner los procesos en común.", description: "Abrimos las puertas de nuestro taller para generar espacios de diálogo que permitan compartir los procesos de creación y situarlos en el contexto del barrio y la ciudad.", pageDescription: "Festivales culturales, coloquios, exposiciones, puertas abiertas de proyectos de investigación y eventos de arte contemporáneo convierten la nave en un espacio de encuentro.", highlights: [
    "Open studios de la residencia de cerámica Brota.",
    "Memorias de agua y barro: coloquio dentro del Festival Cultural CRUZA Carabanchel y Open House Madrid.",
    "Iberoamérica y Carabanchel: diálogos desde el diseño, en el marco de la BID26 de DIMAD, Matadero Madrid.",
    "Exposiciones de artistas y proyectos vinculados a la nave.",
    "Libros a la fresca: presentación pública resultante del seminario de Autoedición con Ana Bustelo.",
  ], image: "/images/program/programa publico/Programa publico_fresca la nave.png", items: [
    { number: "PP—01", type: "Programa público · 2026—2027", title: "Próximas aperturas", subtitle: "La nave como espacio de encuentro", artist: "Fresca. La Nave", description: "Festivales culturales, coloquios, exposiciones, puertas abiertas de proyectos de investigación y eventos de arte contemporáneo para compartir procesos de creación con el barrio y la ciudad.", detail: "Próximamente", image: "/images/program/programa publico/Open Studio_Libros a la fresca_89.png", alt: "Presentación pública de Libros a la fresca en Fresca La Nave" },
  ] },
];

export const getProgramGroup = (slug: string) => programGroups.find((group) => group.slug === slug);
