export type ProgramItem = { number: string; type: string; title: string; subtitle?: string; artist: string; description: string; detail: string; image: string; alt: string; href?: string };
export type ProgramGroup = { slug: string; number: string; kicker: string; title: string; statement: string; description: string; pageDescription?: string; image: string; items: ProgramItem[] };

const talleres: ProgramItem[] = [
  { number: "DM—01", type: "Derivas materiales · Taller", title: "Ese instante de luz", subtitle: "Rayogramas de una deriva", artist: "Ana Paes", description: "Un taller nocturno de fotografía sin cámara para registrar gestos y texturas del entorno. Una deriva por el barrio que continúa en la oscuridad de la nave.", detail: "II edición · Fecha a confirmar", image: "/images/program/derivas materiales/tarjetas/Ese instante de luz_Fresca la nave_rayogramas_fotografia_Madrid.jpeg", alt: "Imagen del taller de rayogramas Ese instante de luz", href: "/talleres/ese-instante-de-luz" },
  { number: "DM—02", type: "Derivas materiales · Taller", title: "Arcillas silvestres y paisaje urbano", artist: "Luka Andeyro + Brenda Ranieri", description: "Un laboratorio para descubrir la arcilla en relación con el territorio y transformar materiales descartados del paisaje urbano en nuevas posibilidades cerámicas.", detail: "II edición · Fecha a confirmar", image: "/images/program/derivas materiales/tarjetas/Arcilla silvestre y paisaje urbano_ceramica_Madrid_Resca la nave .png", alt: "Imagen del taller Arcillas silvestres", href: "/talleres/arcillas-silvestres" },
  { number: "DM—03", type: "Derivas materiales · Taller", title: "Micelio y textil", subtitle: "Micomateriales", artist: "Alejandra Díaz-Guerra", description: "Una aproximación práctica y ritual al micelio como agente vivo de creación, trabajando con fibras naturales y tiempos de crecimiento compartidos.", detail: "Fecha a confirmar", image: "/images/program/derivas materiales/tarjetas/Micelio y textil.jpeg", alt: "Imagen del taller Micelio y textil", href: "/talleres/micelio-y-textil" },
  { number: "DM—04", type: "Derivas materiales · Taller", title: "Criaturas elementales", subtitle: "Activación oracular", artist: "Cecilia Czornogas", description: "Escritura, dibujo y acuarela activados por un oráculo pictórico. Una práctica para jugar con la intuición, el azar y aquello que aparece durante el proceso.", detail: "II edición · Fecha a confirmar", image: "/images/program/derivas materiales/tarjetas/Criaturas elementales.jpeg", alt: "Imagen del taller Criaturas elementales", href: "/talleres/criaturas-elementales" },
  { number: "DM—05", type: "Derivas materiales · Taller", title: "Del papel a la cerámica", artist: "Ana Cano Brookbank", description: "Un acercamiento experimental a la pintura y la gráfica sobre porcelana: estampación, transferencia, impresión, texturas, capas y superposiciones.", detail: "II edición · Fecha a confirmar", image: "/images/program/derivas materiales/tarjetas/Del papel a la porcelana.jpeg", alt: "Imagen del taller Del papel a la cerámica", href: "/talleres/del-papel-a-la-ceramica" },
  { number: "DM—06", type: "Derivas materiales · Taller", title: "El bodegón en la cerámica: La poética de lo cotidiano", artist: "Sophie Aguilera", description: "Un taller para recorrer el proceso completo de una escultura cerámica: modelado, construcción, texturas, decoración a pincel, engobes, esmaltes y cocción.", detail: "II edición · Fecha a confirmar", image: "/images/program/derivas materiales/tarjetas/Bodegones en ceramica.jpeg", alt: "Bodegón contemporáneo en cerámica", href: "/talleres/bodegones-en-porcelana" },
];

export const programGroups: ProgramGroup[] = [
  { slug: "talleres", number: "01", kicker: "Talleres", title: "Derivas materiales", statement: "Seguir lo que la materia propone.", description: "Talleres intensivos de fin de semana para aproximarse a una materia, una técnica o una pregunta desde la experimentación. Artistas y creadoras invitadas comparten sus saberes para observar, recolectar, transformar y dar forma.", pageDescription: "Derivas materiales propone un modo de aproximarse a la creación: partir de una materia, una técnica o una observación y dejar que el proceso abra recorridos inesperados. En cada taller intensivo de fin de semana, una artista o creadora invitada comparte sus saberes y acompaña un proceso de experimentación: observar, recolectar, transformar y dar forma.", image: "/images/program/rayogramas.png", items: talleres },
  { slug: "seminarios", number: "02", kicker: "Procesos cuatrimestrales", title: "Seminarios", statement: "Tiempo para que una práctica encuentre su forma.", description: "Programas de acompañamiento sostenido para desarrollar proyectos propios. Grupos reducidos, tutorías, conversación crítica y herramientas de producción permiten investigar, tomar decisiones y preparar una forma de compartir públicamente cada proceso.", image: "/images/program/procesos cuatrimestrales/Autoedicion.jpeg", items: [
    { number: "SE—01", type: "Seminario · Práctica artística", title: "En obra", subtitle: "Acompañamiento crítico para la práctica artística", artist: "Nacho Martín Silva", description: "Acompañamiento para desarrollar, poner a prueba y compartir un proyecto propio mediante tutorías, crítica de obra, conversación y una exposición colectiva.", detail: "Octubre 2026—marzo 2027", image: "/images/program/procesos cuatrimestrales/seminario en obra/64828F08-43DF-47D4-92A4-3DD8A97CD0C7_1_105_c.jpeg", alt: "Montaje y conversación durante el seminario En obra", href: "/seminarios/en-obra" },
    { number: "SE—02", type: "Seminario · Autoedición", title: "Autoedición", subtitle: "Herramientas para crear y producir una publicación.", artist: "Ana Bustelo", description: "Un proceso acompañado para idear, producir y presentar una publicación personal, desde la investigación y el boceto hasta sus acabados y puesta en público.", detail: "Febrero—mayo 2027", image: "/images/program/procesos cuatrimestrales/seminario-autoedicion/Open Studio_Libros a la fresca_37.png", alt: "Publicaciones realizadas en el seminario de autoedición", href: "/seminarios/autoedicion" },
  ] },
  { slug: "musica", number: "03", kicker: "Música", title: "Derivas sonoras", statement: "Seguir lo que la escucha propone.", description: "Un programa de investigación, creación y encuentro musical coproducido por Nina Polverino y Fresca. La Nave. Laboratorios, conciertos, prácticas de voz y retiros para investigar la música mientras se compone, se ensaya y se transforma.", image: "/images/home/lumbre.jpg", items: [
    { number: "DS—01", type: "Derivas sonoras · Laboratorio", title: "Laboratorio de canciones", artist: "Laicha", description: "Herramientas de composición puestas a disposición de la experimentación colectiva en un encuentro íntimo de creación.", detail: "Noviembre 2026 · 3 h", image: "/images/home/lumbre.jpg", alt: "Laboratorio de canciones de Derivas sonoras" },
    { number: "DS—02", type: "Derivas sonoras · Programa", title: "Música en estado de prueba", artist: "Nina Polverino + Fresca. La Nave", description: "Microconciertos, sesiones experimentales y un retiro creativo donde voz, cuerpo, pensamiento y materia entran en relación.", detail: "Programa 2026—2027", image: "/images/home/exposicion.jpg", alt: "Programa musical en Fresca La Nave" },
  ] },
  { slug: "openings", number: "04", kicker: "Programa público", title: "Programa Público", statement: "Abrir la nave, compartir los procesos.", description: "Exposiciones, open studios y encuentros de fin de semana donde las investigaciones desarrolladas en Fresca entran en relación con el barrio y con nuevos públicos. Un espacio para mostrar obra terminada, pero también pruebas, materiales y procesos todavía abiertos.", image: "/images/home/open-studio.jpg", items: [
    { number: "OP—01", type: "Open House Madrid", title: "Lo que decanta", artist: "Arcillas de Carabanchel · Brenda Ranieri", description: "Piezas e investigación material que hacen visible el tránsito del suelo urbano al taller, del sedimento a la forma.", detail: "26—27 septiembre 2026", image: "/images/home/open-studio.jpg", alt: "Open studio en Fresca La Nave" },
    { number: "OP—02", type: "CRUZA Carabanchel", title: "Ese instante de luz", artist: "Ana Paes + Brenda Ranieri", description: "Rayogramas, autoedición y arcillas locales reúnen dos temporalidades del paisaje: la huella inmediata de la luz y el tiempo lento de la decantación.", detail: "3—4 octubre 2026", image: "/images/program/rayogramas.png", alt: "Exposición de rayogramas en Fresca La Nave" },
  ] },
];

export const getProgramGroup = (slug: string) => programGroups.find((group) => group.slug === slug);
