export type WorkshopEntry = {
  slug: string;
  number: string;
  cardTitle: string;
  title: string;
  byline: string;
  edition?: string;
  question: string;
  intro: string;
  context: string;
  date: string;
  duration: string;
  schedule: string;
  place: string;
  group: string;
  price: string;
  includes: string;
  journeyTitle?: string;
  infoTitle?: string;
  heroImage: string;
  images: string[];
  extraImages?: string[];
  steps: Array<{ number?: string; title: string; text: string }>;
  tutors: Array<{ name: string; text: string }>;
};

export const workshops: WorkshopEntry[] = [
  {
    slug: "ese-instante-de-luz", number: "DM—01", cardTitle: "Ese instante de luz", title: "Ese instante de luz. Lo que la materia revela", byline: "Rayogramas de una deriva con Ana Paes", edition: "II edición",
    question: "¿Qué imágenes aparecen cuando la luz registra los materiales de una deriva?",
    intro: "Un taller nocturno y experimental de rayogramas para registrar gestos y texturas del entorno a través de la fotografía sin cámara.",
    context: "Caminaremos por la Cuña Verde recolectando fragmentos y restos. De vuelta en la nave, trabajaremos en la oscuridad con exposiciones breves de luz, materiales secos y agua decantada de arcilla de Carabanchel.",
    infoTitle: "Registrar los gestos del paisaje urbano",
    date: "2 de octubre de 2026", duration: "4 horas", schedule: "Viernes · 19—23 h", place: "Fresca. La Nave · Carabanchel, Madrid", group: "Máximo 10 participantes · Sin experiencia previa", price: "60 €", includes: "Materiales incluidos",
    heroImage: "/images/program/paginas/ese instante de luz/Rayogramas_Taller Ana Paes_Fresca_19.jpeg", images: [
      "/images/program/paginas/ese instante de luz/Taller rayogramas_Fresca. La nave_ana Paes62.jpeg", "/images/program/paginas/ese instante de luz/DSC02974.JPG", "/images/program/paginas/ese instante de luz/DSC03015.JPG", "/images/program/paginas/ese instante de luz/Rayogramas_Taller Ana Paes_Fresca_10.jpeg", "/images/program/paginas/ese instante de luz/Rayogramas_Taller Ana Paes_Fresca_11.jpeg", "/images/program/paginas/ese instante de luz/Rayogramas_Taller Ana Paes_Fresca_22.jpeg", "/images/program/paginas/ese instante de luz/Rayogramas_Taller Ana Paes_Fresca_9.jpeg", "/images/program/paginas/ese instante de luz/Taller rayogramas_Fresca. La nave_ana Paes11.jpeg", "/images/program/paginas/ese instante de luz/Taller rayogramas_Fresca. La nave_ana Paes3.jpg", "/images/program/paginas/ese instante de luz/Taller rayogramas_Fresca. La nave_ana Paes32.jpeg", "/images/program/paginas/ese instante de luz/Taller rayogramas_Fresca. La nave_ana Paes47.jpeg", "/images/program/paginas/ese instante de luz/Taller rayogramas_Fresca. La nave_ana Paes54.jpeg", "/images/program/paginas/ese instante de luz/Taller rayogramas_Fresca. La nave_ana Paes56.jpeg", "/images/program/paginas/ese instante de luz/Taller rayogramas_Fresca. La nave_ana Paes61.jpeg", "/images/program/paginas/ese instante de luz/Taller rayogramas_Fresca. La nave_ana Paes64.jpeg", "/images/program/paginas/ese instante de luz/Taller rayogramas_Fresca. La nave_ana Paes66.jpeg", "/images/program/paginas/ese instante de luz/Taller rayogramas_Fresca. La nave_ana Paes67.jpeg", "/images/program/paginas/ese instante de luz/Taller rayogramas_Fresca. La nave_ana Paes76.jpeg", "/images/program/paginas/ese instante de luz/Taller rayogramas_Fresca. La nave_ana Paes77.jpeg", "/images/program/paginas/ese instante de luz/Taller rayogramas_Fresca. La nave_ana Paes78.jpeg", "/images/program/paginas/ese instante de luz/Taller rayogramas_Fresca. La nave_ana Paes8.jpeg", "/images/program/paginas/ese instante de luz/Taller rayogramas_Fresca. La nave_ana Paes82.jpeg", "/images/program/paginas/ese instante de luz/Taller rayogramas_Fresca. La nave_ana Paes9.jpeg", "/images/program/paginas/ese instante de luz/Taller rayogramas_Fresca. La nave_ana Paes97.jpeg", "/images/program/paginas/ese instante de luz/Taller rayogramas_Fresca. La nave_ana Paes99.jpeg",
    ],
    steps: [{ title: "Derivar", text: "Caminar, observar y recoger fragmentos del paisaje urbano." }, { title: "Preparar", text: "Disponer los materiales y transformar la nave en laboratorio oscuro." }, { title: "Exponer", text: "Registrar huellas mediante breves exposiciones de luz." }, { title: "Repetir", text: "Atender al azar, al ritmo y a lo inesperado de cada imagen." }],
    tutors: [{ name: "Ana Paes", text: "Ana Paes (A Guarda, 1982) es artista visual y docente. Licenciada en Historia del Arte por la USC y con máster propio en Historia y Estética de la Cinematografía por la UVA, está especializada en técnicas analógicas y prácticas ecosostenibles. Su obra se centra en la materialidad y las relaciones con la naturaleza, explorando narrativas no lineales y el simbolismo cotidiano. Su trabajo ha podido verse en el Centro de Arte Moderno de Tetuán, La Casa Encendida en Madrid, la Fundación Luis Seoane en A Coruña, Loading Fest en Porto y Medialab Prado, entre otros. La publicación de su último proyecto formó parte de la selección de fotolibros de PHotoESPAÑA 2024. También participa en proyectos educativos y artísticos, destacando su labor como docente en el Laboratorio de Fotografía de La Casa Encendida y el proyecto colaborativo internacional Malas Hierbas con la Universidad Rey Juan Carlos." }],
  },
  {
    slug: "arcillas-silvestres-y-paisaje-urbano", number: "DM—02", cardTitle: "Arcillas silvestres y paisaje urbano", title: "Arcillas silvestres y materiales del paisaje urbano", byline: "Con Luka Andeyro y Brenda Ranieri", edition: "II edición",
    question: "¿Cómo puede un material descartado encontrar una nueva vida en la práctica cerámica?",
    intro: "Un laboratorio práctico para descubrir la arcilla en relación con el territorio, explorar los recursos del paisaje urbano y experimentar las posibilidades de la cerámica expandida.",
    context: "La propuesta cruza la investigación geológica y situada de Luka Andeyro con la cartografía material de Carabanchel desarrollada por Brenda Ranieri.",
    infoTitle: "Recolección, clasificación y creación en un acercamiento a la geología local y paisaje urbano.",
    date: "27, 28 y 29 de noviembre de 2026", duration: "16 horas", schedule: "Viernes 16—20 h · Sábado 10—18 h · Domingo 10—14 h", place: "Fresca. La Nave · Carabanchel, Madrid", group: "Máximo 10 participantes · Sin experiencia previa", price: "260 €", includes: "Materiales y cocción incluidos",
    heroImage: "/images/program/paginas/arcillas silvestres y paisaje urbano/Arcilla y paisaje urbano_Brenda Ranieri_Luka Andeyro_33.png", images: [
      "/images/program/paginas/arcillas silvestres y paisaje urbano/Arcilla y paisaje urbano_Brenda Ranieri_Luka Andeyro_34.png", "/images/program/paginas/arcillas silvestres y paisaje urbano/4B8829C4-31EC-40FA-9778-02C2B55A0C22_1_105_c.jpeg", "/images/program/paginas/arcillas silvestres y paisaje urbano/6A913430-9C9E-4364-8FE1-AF81FA73AD44_1_105_c.jpeg", "/images/program/paginas/arcillas silvestres y paisaje urbano/6A9AB489-902F-4011-A423-5386D216D366_1_105_c.jpeg", "/images/program/paginas/arcillas silvestres y paisaje urbano/6F0DDF34-E306-4CD3-BEF0-7FBC0095812E_1_105_c.jpeg", "/images/program/paginas/arcillas silvestres y paisaje urbano/Arcilla y paisaje urbano_Brenda Ranieri_Luka Andeyro_14.png", "/images/program/paginas/arcillas silvestres y paisaje urbano/Arcilla y paisaje urbano_Brenda Ranieri_Luka Andeyro_16.png", "/images/program/paginas/arcillas silvestres y paisaje urbano/Arcilla y paisaje urbano_Brenda Ranieri_Luka Andeyro_2.png", "/images/program/paginas/arcillas silvestres y paisaje urbano/Arcilla y paisaje urbano_Brenda Ranieri_Luka Andeyro_22.png", "/images/program/paginas/arcillas silvestres y paisaje urbano/Arcilla y paisaje urbano_Brenda Ranieri_Luka Andeyro_5.png", "/images/program/paginas/arcillas silvestres y paisaje urbano/Arcilla y paisaje urbano_Brenda Ranieri_Luka Andeyro_7.png", "/images/program/paginas/arcillas silvestres y paisaje urbano/BB5FE83E-D266-4631-8C4B-8C78E29EB673_1_105_c.jpeg", "/images/program/paginas/arcillas silvestres y paisaje urbano/EE0872B8-A9B5-4271-B850-CEBFA3F5FEE5_1_105_c.jpeg", "/images/program/paginas/arcillas silvestres y paisaje urbano/EE3C29C7-314B-4BFD-B6B4-CA7ACE5771F5_1_105_c.jpeg", "/images/program/paginas/arcillas silvestres y paisaje urbano/FE3E2CF7-8A9B-4E50-8083-7E02B115A65F_1_105_c.jpeg",
    ],
    extraImages: ["/images/program/paginas/arcillas silvestres y paisaje urbano/Arcilla y paisaje urbano_Brenda Ranieri_Luka Andeyro_29.png"],
    steps: [{ title: "Leer el territorio", text: "Atender a grietas, sedimentos, rastros de agua, metales y objetos desplazados." }, { title: "Recolectar", text: "Recoger muestras con potencial cerámico y construir una cartografía situada." }, { title: "Experimentar", text: "Analizar arcillas locales, residuos minerales y elementos encontrados." }, { title: "Dar forma", text: "Elaborar piezas que conecten observación, materia, memoria y territorio." }],
    tutors: [{ name: "Luka Andeyro", text: "Luka Andeyro (Madrid, 1985) llegó a la cerámica a través de movimientos sucesivos. Siempre sintió una aspiración escultórica, inicialmente canalizada mediante estudios de arquitectura. Posteriormente, durante su formación en Bellas Artes, descubrió la plasticidad del barro: una materia cálida e informe que todo lo contiene. En 2013 se especializó con un máster en Environmental Art durante una estancia de cinco años en la Aalto University de Helsinki, experiencia que le permitió integrar una vivencia nórdica de la naturaleza que sigue atravesando su práctica. Su trabajo se sitúa en una orogénesis íntima, donde la materia no funciona como soporte sino como acontecimiento. Trabaja únicamente con arcillas silvestres y rocas madres de arcilla recolectadas por ella misma. Cada pieza constituye una condensación temporal donde el tiempo profundo de la Tierra se pliega, por un instante, a la experiencia humana. Su trabajo no busca representar la naturaleza, sino permitir que la materia acontezca como relación." }, { name: "Brenda Ranieri", text: "Brenda Ranieri (Buenos Aires, 1988) es artista visual y ceramista afincada en Madrid. Licenciada en Publicidad por la UCES de Buenos Aires y Ceramista por la Escuela de Cerámica de la Moncloa, su práctica se centra en la investigación matérica y en la cerámica contemporánea como forma de lectura sensible del territorio. Su trabajo explora las relaciones entre lo humano y lo más-que-humano desde la escucha, la coexistencia y el cuidado. Desde su taller en Carabanchel, Fresca. La Nave —espacio de creación contemporánea del que es fundadora y directora— desarrolla una práctica situada basada en la recolección y transformación de materiales del entorno, como arcillas locales, restos metálicos y fragmentos industriales. Ha expuesto en muestras colectivas en Conde Duque y Matadero Madrid, así como en Doble Erre con Ventana Project, Artelier 21 Gallery, Cerúleo y Solaina. También ha participado en Cruza Carabanchel y Open House Madrid, y forma parte del proyecto Iberoamérica y Carabanchel: Diálogos del diseño, dentro de la Bienal Iberoamericana de Diseño 2026." }],
  },
  {
    slug: "micelio-y-textil", number: "DM—03", cardTitle: "Micelio y textil", title: "Micelio y textil. Micomateriales", byline: "Con Alejandra Díaz-Guerra",
    question: "¿Cómo crear con un material vivo y acompañar sus propios tiempos de transformación?",
    intro: "Una aproximación práctica y ritual al micelio como agente vivo de creación, trabajando con fibras naturales y tiempos de crecimiento compartidos.",
    context: "En la primera sesión, Alejandra compartirá su investigación sobre las posibilidades del micelio y las fibras, y realizaremos la inoculación de textiles. Durante el intervalo, las piezas permanecerán en la nave y se hará un seguimiento de su desarrollo. En la segunda sesión, se observarán los resultados, se abrirá un espacio de conversación en torno al proceso y finalizaremos con la creación de una obra colectiva inoculada, como ejercicio de co-creación con el micelio. Incluye todos los materiales y picoteo.",
    infoTitle: "Un laboratorio para acercarnos a los micomateriales desde las nuevas ecologías y la co-creación.",
    date: "21 de noviembre y 12 de diciembre de 2026", duration: "2 sesiones", schedule: "21 de noviembre y 12 de diciembre · 10—14 h", place: "Fresca. La Nave · Carabanchel, Madrid", group: "Máximo 10 participantes", price: "75 €", includes: "Materiales y picoteo incluidos",
    heroImage: "/images/program/paginas/micelo y textil/Alejandra Diaz Guerra-micelio--.jpg", images: [
      "/images/program/paginas/micelo y textil/Alejandra Diaz Guerra-micelio_2026.jpeg",
      "/images/program/paginas/micelo y textil/A_lejandra Diaz Guerra-micelio_2026.jpeg",
      "/images/program/paginas/micelo y textil/Alejandra Diaz Guerra-micelio.jpeg",
      "/images/program/paginas/micelo y textil/SaveClip.App_552694010_18527776723030561_8631674629529842615_n.jpg",
      "/images/program/paginas/micelo y textil/SaveClip.App_553024579_18527776705030561_3982006346998888570_n.jpg",
      "/images/program/paginas/micelo y textil/SaveClip.App_553244914_18527776696030561_5014726968304923810_n.jpg",
      "/images/program/paginas/micelo y textil/SaveClip.App_553364367_18527776714030561_3787621888316888613_n.jpg",
      "/images/program/paginas/micelo y textil/SaveClip.App_553377491_18527776678030561_3863961697248700237_n.jpg",
      "/images/program/paginas/micelo y textil/SaveClip.App_553672064_18527776732030561_719152737552981190_n.jpg",
      "/images/program/paginas/micelo y textil/SaveClip.App_554379342_18527776741030561_1991864047360888132_n.jpg",
      "/images/program/paginas/micelo y textil/SaveClip.App_590399886_18543312055030561_3774633409374509762_n.jpg",
      "/images/program/paginas/micelo y textil/SaveClip.App_622091249_18552499591030561_3781729157443765690_n.jpg",
      "/images/program/paginas/micelo y textil/SaveClip.App_622158070_18552499600030561_6038431952675167444_n.jpg",
      "/images/program/paginas/micelo y textil/SaveClip.App_622161275_18552499618030561_3493430755996148122_n.jpg",
    ],
    steps: [{ title: "Descubrir", text: "Acercarse a la investigación de Alejandra sobre micelio y fibras." }, { title: "Inocular", text: "Preparar e inocular textiles de fibras naturales." }, { title: "Acompañar", text: "Observar el crecimiento durante el intervalo entre sesiones." }, { title: "Co-crear", text: "Cerrar con una obra colectiva inoculada y una conversación compartida." }],
    tutors: [{ name: "Alejandra Díaz-Guerra", text: "Alejandra Díaz-Guerra Acedo (Madrid, 1994) es artista interdisciplinar y comisaria. Su formación académica en filosofía, estética y comisariado define su interés por la mediación y la enseñanza a través del arte. Su práctica combina investigación teórica y experimentación material, y atiende especialmente a las relaciones entre organismos vivos, cerámica, fibras y procesos de transformación. En sus investigaciones recientes trabaja con micelio inoculado en piezas cerámicas y textiles, observando la porosidad, el crecimiento, los tiempos de latencia y la capacidad del material vivo para intervenir en la forma. También ha desarrollado proyectos curatoriales vinculados con la naturaleza urbana y el territorio, entre ellos la residencia En barrio en Carabanchel." }],
  },
  {
    slug: "criaturas-elementales", number: "DM—04", cardTitle: "Criaturas elementales", title: "Criaturas elementales. Práctica híbrida de escritura, dibujo y acuarela", byline: "Activación oracular con Cecilia Czornogas", edition: "II edición",
    question: "¿Qué aparece cuando la imagen, la escritura y el azar trabajan juntos?",
    intro: "Una práctica híbrida de escritura, dibujo y acuarela activada por un oráculo pictórico creado por Cecilia Czornogas.",
    context: "Cada participante entra en diálogo con las imágenes a partir de una pregunta. El azar funciona como estrategia para soltar la mano y dejar que el sentido emerja durante el proceso.",
    infoTitle: "Te invitamos a compartir con nosotras esta sesión sensible y creativa",
    date: "11 de diciembre de 2026", duration: "3 horas", schedule: "Viernes · 18—21 h", place: "Fresca. La Nave · Carabanchel, Madrid", group: "Máximo 10 participantes · Sin experiencia previa", price: "50 €", includes: "Materiales y picoteo incluidos",
    heroImage: "/images/program/paginas/criaturas elementales/Taller criaturas elementales_Cecz_Fresca la nave22.png", images: [
      "/images/program/paginas/criaturas elementales/Taller criaturas elementales_Cecz_Fresca la nave2.jpeg", "/images/program/paginas/criaturas elementales/IMG_5175.JPG", "/images/program/paginas/criaturas elementales/Taller criaturas elementales_Cecz_Fresca la nave1.jpeg", "/images/program/paginas/criaturas elementales/Taller criaturas elementales_Cecz_Fresca la nave10.jpeg", "/images/program/paginas/criaturas elementales/Taller criaturas elementales_Cecz_Fresca la nave13.jpeg", "/images/program/paginas/criaturas elementales/Taller criaturas elementales_Cecz_Fresca la nave14.jpeg", "/images/program/paginas/criaturas elementales/Taller criaturas elementales_Cecz_Fresca la nave15.jpeg", "/images/program/paginas/criaturas elementales/Taller criaturas elementales_Cecz_Fresca la nave16.JPG", "/images/program/paginas/criaturas elementales/Taller criaturas elementales_Cecz_Fresca la nave17.png", "/images/program/paginas/criaturas elementales/Taller criaturas elementales_Cecz_Fresca la nave18.png", "/images/program/paginas/criaturas elementales/Taller criaturas elementales_Cecz_Fresca la nave19.png", "/images/program/paginas/criaturas elementales/Taller criaturas elementales_Cecz_Fresca la nave20.png", "/images/program/paginas/criaturas elementales/Taller criaturas elementales_Cecz_Fresca la nave21.png", "/images/program/paginas/criaturas elementales/Taller criaturas elementales_Cecz_Fresca la nave23.png", "/images/program/paginas/criaturas elementales/Taller criaturas elementales_Cecz_Fresca la nave24.png", "/images/program/paginas/criaturas elementales/Taller criaturas elementales_Cecz_Fresca la nave3.jpeg", "/images/program/paginas/criaturas elementales/Taller criaturas elementales_Cecz_Fresca la nave5.jpeg", "/images/program/paginas/criaturas elementales/Taller criaturas elementales_Cecz_Fresca la nave6.jpeg", "/images/program/paginas/criaturas elementales/Taller criaturas elementales_Cecz_Fresca la nave7.jpeg", "/images/program/paginas/criaturas elementales/Taller criaturas elementales_Cecz_Fresca la nave8.jpeg", "/images/program/paginas/criaturas elementales/Taller criaturas elementales_Cecz_Fresca la nave9.jpeg",
    ],
    steps: [{ title: "Preguntar", text: "Comenzar con una pregunta o un tema que acompañe la experiencia." }, { title: "Consultar", text: "Entrar en diálogo con las imágenes del oráculo pictórico." }, { title: "Desplegar", text: "Trabajar con escritura automática, dibujo y pintura desde la mancha." }, { title: "Compartir", text: "Abrir la práctica individual al cruce y la puesta en común grupal." }],
    tutors: [{ name: "Cecilia Czornogas", text: "Cecilia Czornogas es una artista transdisciplinaria nacida en Buenos Aires, Argentina. Su formación integra actuación, música y artes visuales: es licenciada en Actuación por la Universidad Nacional de las Artes (UNA), estudió Astrología en Casa XI y completó el Máster en Artes y Profesiones Artísticas en UC3M–CBA (Madrid). Tras iniciar su trayectoria en teatro, cine y televisión —con una nominación al Premio Florencio Sánchez a Mejor Actriz Revelación en 2012—, expandió su práctica hacia el performance y las intervenciones artísticas en galerías y espacios no convencionales.\n\nEn el área de la música, formaron junto a su hermano, Ignacio Salvadores, la banda Hermanos Mckenzie, donde Cecilia era la voz principal. La banda se presentó en las mejores salas de Buenos Aires, haciendo giras por el resto de Argentina y Europa.\n\nTras la disolución de Hermanos Mckenzie, siguió su camino como solista bajo el seudónimo de CECZ; iniciando una carrera en el mundo de la curaduría musical, algo por lo que siempre tuvo devoción. Actualmente, es residente en Radio Relativa (Madrid) con sus radio performances Jardín Secreto y Excelente Servicio.\n\nEn los últimos años, su trabajo se ha volcado especialmente a las artes visuales, explorando el collage y la acuarela como lenguajes de cruce entre intuición, imagen y pensamiento simbólico. Entre 2024 y 2026 participó en las exposiciones colectivas Kolash (Espacio Cómplices, Madrid), Accidentes (Círculo de Bellas Artes, Madrid), Espectro (Espacio Enredo, Madrid) y The Archive of Stars (Halo Studio, Berlín).\n\nHa creado Criaturas Elementales, un singular juego oracular de cartas, pintado íntegramente en acuarela, que invita al despliegue de la imaginación y la creatividad, guiado por la intuición y el azar.\n\nSu producción se nutre de una práctica híbrida que articula lo visual con lo performativo, lo musical y lo esotérico, entendiendo el arte como un campo expandido de experimentación." }],
  },
  {
    slug: "experimentacion-pictorica-sobre-ceramica", number: "DM—05", cardTitle: "Experimentación pictórica sobre cerámica", title: "Experimentación pictórica sobre cerámica", byline: "Con Ana Cano Brookbank", edition: "II edición",
    question: "¿Cómo convertir un recurso gráfico en un camino experimental de creación pictórica?",
    intro: "Un taller intensivo de experimentación pictórica sobre cerámica.",
    context: "Durante un día y medio trabajaremos desde una metodología creativa con estampación, impresión e intervención pictórica sobre cerámica. Construiremos un archivo de huellas, líneas, manchas, repeticiones, capas y accidentes que cada participante podrá combinar experimentando en una pieza plana-escultórica en alta temperatura (objeto de mesa o de pared).",
    journeyTitle: "Experimentar, combinar, componer, repetir.",
    infoTitle: "Experimentación pictórica intensiva sobre cerámica",
    date: "31 de octubre y 1 de noviembre de 2026", duration: "Un día y medio", schedule: "Horario a confirmar", place: "Fresca. La Nave · Carabanchel, Madrid", group: "Máximo 10 participantes", price: "140 €", includes: "Materiales y cocción incluidos",
    heroImage: "/images/program/paginas/del papel a la cerámica/Taller del papel a la ceramica_Fresca la nave_Ana Cano9.jpeg", images: [
      "/images/program/paginas/del papel a la cerámica/Taller del papel a la ceramica_Fresca la nave_Ana Cano5.jpeg", "/images/program/paginas/del papel a la cerámica/Taller del papel a la ceramica_Fresca la nave_Ana Cano1.jpeg", "/images/program/paginas/del papel a la cerámica/Taller del papel a la ceramica_Fresca la nave_Ana Cano10.jpeg", "/images/program/paginas/del papel a la cerámica/Taller del papel a la ceramica_Fresca la nave_Ana Cano11.jpeg", "/images/program/paginas/del papel a la cerámica/Taller del papel a la ceramica_Fresca la nave_Ana Cano2.jpeg", "/images/program/paginas/del papel a la cerámica/Taller del papel a la ceramica_Fresca la nave_Ana Cano3.jpeg", "/images/program/paginas/del papel a la cerámica/Taller del papel a la ceramica_Fresca la nave_Ana Cano4.jpeg", "/images/program/paginas/del papel a la cerámica/Taller del papel a la ceramica_Fresca la nave_Ana Cano6.jpeg", "/images/program/paginas/del papel a la cerámica/Taller del papel a la ceramica_Fresca la nave_Ana Cano7.jpeg", "/images/program/paginas/del papel a la cerámica/Taller del papel a la ceramica_Fresca la nave_Ana Cano8.jpeg",
    ],
    steps: [{ title: "Experimentar", text: "Explorar estampaciones, impresiones e intervenciones pictóricas sobre cerámica." }, { title: "Combinar", text: "Relacionar huellas, líneas, manchas, capas y accidentes dentro de un archivo gráfico propio." }, { title: "Componer", text: "Seleccionar y articular los recursos experimentados en una pieza plana-escultórica en alta temperatura (objeto de mesa o de pared)." }, { title: "Repetir", text: "Volver sobre los gestos y procedimientos para descubrir nuevas posibilidades pictóricas." }],
    tutors: [{ name: "Ana Cano Brookbank", text: "Ana Cano Brookbank (Madrid, 1987) es artista plástica multidisciplinar. Licenciada en Bellas Artes por la Universidad Complutense de Madrid, completó parte de su formación en L’École Nationale Supérieure des Beaux-Arts de París y cursó estudios de cerámica en la Escuela de Cerámica de la Moncloa, donde actualmente es profesora. Su trabajo se desplaza entre la pintura, la ilustración, el grabado y la cerámica, utilizando el color, las formas simples y el espacio como recursos compositivos. Ha participado en residencias de pintura en Polonia, ferias internacionales de cerámica en España y Japón, performances e instalaciones, y ha expuesto en espacios como FLECHA, Espacio B y Aspa Contemporary." }],
  },
  {
    slug: "sirviendo-un-plato-bodegon", number: "DM—06", cardTitle: "Sirviendo", title: "Sirviendo. Un plato-bodegón", byline: "Con Sophie Aguilera",
    question: "¿Qué cuentan los objetos cuando los ponemos en escena?",
    intro: "Un taller para realizar un plato-bodegón en arcilla: soporte, marco y pequeño escenario donde formas cercanas al imaginario de cada participante puedan empezar a contar algo.",
    context: "Frutas, flores, alimentos, envoltorios u objetos cotidianos convivirán en un plato-bodegón contemporáneo de cerámica. Sophie acompañará el proceso desde la idea, las técnicas de modelado, pintura y esmaltado de las piezas. Retirarás tu plato-bodegón listo unos días después.",
    date: "16 y 23 de enero de 2027", duration: "12 horas · 2 sesiones", schedule: "16 de enero, 10—18 h · 23 de enero, 10—14 h", place: "Fresca. La Nave · Carabanchel, Madrid", group: "Máximo 10 participantes", price: "250 €", includes: "Materiales, herramientas y hornadas incluidos",
    journeyTitle: "Sirviendo un plato-bodegón",
    infoTitle: "Crear una pieza de cerámica desde cero",
    heroImage: "/images/program/paginas/bodegones en ceramica/Bodegones en cerámica_Sophie Aguilera22.jpeg", images: [
      "/images/program/derivas materiales/paginas/bodegones en ceramica/LaVida+EsDomingo_def1.jpeg", "/images/program/derivas materiales/paginas/bodegones en ceramica/detalle.jpeg",
      "/images/program/paginas/bodegones en ceramica/Bodegones en cerámica_Sophie Aguilera31.jpeg", "/images/program/paginas/bodegones en ceramica/Bodegones en cerámica_Sophie Aguilera16.jpeg", "/images/program/paginas/bodegones en ceramica/Bodegones en cerámica_Sophie Aguilera17.jpeg", "/images/program/paginas/bodegones en ceramica/Bodegones en cerámica_Sophie Aguilera19.jpeg", "/images/program/paginas/bodegones en ceramica/Bodegones en cerámica_Sophie Aguilera20.jpeg", "/images/program/paginas/bodegones en ceramica/Bodegones en cerámica_Sophie Aguilera21.jpeg", "/images/program/paginas/bodegones en ceramica/Bodegones en cerámica_Sophie Aguilera24.jpeg", "/images/program/paginas/bodegones en ceramica/Bodegones en cerámica_Sophie Aguilera25.jpeg", "/images/program/paginas/bodegones en ceramica/Bodegones en cerámica_Sophie Aguilera26.jpeg", "/images/program/paginas/bodegones en ceramica/Bodegones en cerámica_Sophie Aguilera27.jpeg", "/images/program/paginas/bodegones en ceramica/Bodegones en cerámica_Sophie Aguilera29.jpeg", "/images/program/paginas/bodegones en ceramica/Bodegones en cerámica_Sophie Aguilera30.jpeg", "/images/program/paginas/bodegones en ceramica/Bodegones en cerámica_Sophie Aguilera32.jpeg", "/images/program/paginas/bodegones en ceramica/Bodegones en cerámica_Sophie Aguilera33.jpeg", "/images/program/paginas/bodegones en ceramica/Bodegones en cerámica_Sophie Aguilera34.jpeg", "/images/program/paginas/bodegones en ceramica/Bodegones en cerámica_Sophie Aguilera35.jpeg", "/images/program/paginas/bodegones en ceramica/Bodegones en cerámica_Sophie Aguilera36.jpeg", "/images/program/paginas/bodegones en ceramica/Bodegones en cerámica_Sophie Aguilera38.jpeg", "/images/program/paginas/bodegones en ceramica/Bodegones en cerámica_Sophie Aguilera39.jpeg",
    ],
    steps: [{ number: "01", title: "Componer", text: "Pensar el plato como una escena y definir sus componentes." }, { number: "03", title: "Modelar", text: "Construir el plato y los elementos seleccionados mediante las técnicas de modelado propuestas por la artista." }, { number: "04", title: "Pintar", text: "Trabajar a pincel los matices de la pieza con engobes de diferentes colores." }, { number: "05", title: "Esmaltar", text: "En la última sesión esmaltaremos la pieza ya bizcochada. Te avisaremos unos días después para venir a buscar la pieza." }],
    tutors: [{ name: "Sophie Aguilera", text: "Sophie Aguilera Lester (Londres, 1984) es una artista española afincada en Barcelona. Su proceso creativo se mueve entre la figuración clásica y la posmodernidad, y su trabajo reciente se centra en la investigación y revisión de bodegones y naturalezas muertas inspiradas en la tradicional cerámica de engaño o trompe-l’œil. Trabaja minuciosas formas florales, frutas y telas con las que crea nuevos escenarios contemporáneos inspirados en la tradición y el virtuosismo clásico. Ha participado en numerosas exposiciones nacionales e internacionales. En 2018 fue invitada a representar a España en la Bienal Europea Contexto Cerámico, en la isla danesa de Bornholm. En 2019 recibió el Premio Nacional de Cerámica como mejor artista emergente de la Asociación Española de Ciudades de la Cerámica y fue seleccionada como artista residente en la Fundación Archie Bray." }],
  },
];

export const getWorkshop = (slug: string) => workshops.find((workshop) => workshop.slug === slug);
